[package]
name = "seify"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Shiny Samples from your SDR"

[features]
default = ["rtlsdr", "hackrf"]
rtlsdr = ["dep:rtlsdr-rs"]
hackrf = ["dep:hackrfone"]
aaronia = ["dep:aaronia-rtsa"]
soapy = ["dep:soapysdr"]

[dependencies]
hackrfone = { git = "https://github.com/newAM/hackrfone", version = "0.2.3", optional = true }
rtlsdr-rs = { git = "https://github.com/ccostes/rtl-sdr-rs", optional = true }
aaronia-rtsa = { version = "0.0.1", optional = true }
soapysdr = { version = "0.3.2", optional = true }
thiserror = "1.0.38"
