[package]
name = "seify"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Shiny Samples from your SDR"

[features]
default = ["rtlsdr", "aaronia", "soapy", "aaronia_http"]
rtlsdr = ["dep:rtlsdr-rs"]
hackrf = ["dep:hackrfone"]
aaronia = ["dep:aaronia-rtsa"]
aaronia_http = ["dep:async-native-tls", "dep:http", "dep:hyper", "dep:tokio", "dep:futures"]
soapy = ["dep:soapysdr"]

[dependencies]
aaronia-rtsa = { path = "/home/basti/src/aaronia-rtsa/", optional = true }
async-io = "1.6.0"
async-native-tls = { version = "0.4", optional = true }
async-net = "1.5.0"
futures = { version = "0.3.18", optional = true }
hackrfone = { git = "https://github.com/newAM/hackrfone", version = "0.2.3", optional = true }
http = { version = "0.2", optional = true }
hyper = { version = "0.14", default-features = false, features = ["client", "http1", "stream", "tcp"], optional = true}
nom = "7.1.2"
num-complex = "0.4.2"
rtlsdr-rs = { path = "crates/rtl-sdr-rs", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
serde_with = "2.2.0"
soapysdr = { version = "0.3.2", optional = true }
thiserror = "1.0.38"
tokio = { version = "1", features = ["rt", "net"], optional= true}

[dev-dependencies]
env_logger = "0.10.0"
gnuplot = "0.0.37"
rustfft = "6.1.0"
