[package]
name = "seify"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Shiny Samples from your SDR"

[features]
default = ["rtlsdr"]
rtlsdr = ["dep:rtlsdr-rs"]
hackrf = ["dep:hackrfone"]
aaronia = ["dep:aaronia-rtsa"]
soapy = ["dep:soapysdr"]

[dependencies]
aaronia-rtsa = { version = "0.0.1", optional = true }
hackrfone = { git = "https://github.com/newAM/hackrfone", version = "0.2.3", optional = true }
nom = "7.1.2"
num-complex = "0.4.2"
rtlsdr-rs = { path = "crates/rtl-sdr-rs", optional = true }
soapysdr = { version = "0.3.2", optional = true }
thiserror = "1.0.38"

[dev-dependencies]
env_logger = "0.10.0"
gnuplot = "0.0.37"
rustfft = "6.1.0"
